openapi: 3.0.1
info:
  title: Frontend for AWS
  description: Web Frontend for AWS Services
  version: 0.11.5
paths:
  /security_log/intrusion_attempts:
    get:
      parameters:
      - name: service
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Apache
          - Nginx
          - Ssh
      - name: location
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Home
          - Cloud
      - name: ndays
        in: query
        required: false
        schema:
          nullable: true
          type: integer
      responses:
        '200':
          description: Intrusion Attempts
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/map_script.js:
    get:
      responses:
        '200':
          description: Map Drawing Script
          content:
            text/javascript:
              schema:
                type: string
  /security_log/intrusion_attempts/all:
    get:
      parameters:
      - name: service
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Apache
          - Nginx
          - Ssh
      - name: location
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Home
          - Cloud
      - name: ndays
        in: query
        required: false
        schema:
          nullable: true
          type: integer
      responses:
        '200':
          description: All Intrusion Attempts
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/intrusion_log:
    get:
      parameters:
      - name: service
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Apache
          - Nginx
          - Ssh
      - name: server
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Home
          - Cloud
      - name: offset
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      - name: limit
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      responses:
        '200':
          description: Intrusion Logs
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/IntrusionLog'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntrusionLogUpdate'
        required: true
      responses:
        '201':
          description: Intrusion Log Post
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/host_country:
    get:
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      - name: limit
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      responses:
        '200':
          description: Host Countries
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/HostCountry'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostCountryUpdate'
        required: true
      responses:
        '201':
          description: Host Country Post
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/cleanup:
    post:
      responses:
        '201':
          description: Host Country Cleanup
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/HostCountry'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/user:
    get:
      responses:
        '200':
          description: Logged User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedUser'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/log_messages:
    get:
      parameters:
      - name: log_level
        in: query
        required: false
        schema:
          nullable: true
          type: string
          enum:
          - Debug
          - Info
          - Warning
          - Error
      - name: log_unit
        in: query
        required: false
        schema:
          nullable: true
          type: string
      - name: min_date
        in: query
        required: false
        schema:
          format: date-time
          nullable: true
          type: string
      - name: max_date
        in: query
        required: false
        schema:
          format: date-time
          nullable: true
          type: string
      - name: limit
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      - name: offset
        in: query
        required: false
        schema:
          nullable: true
          type: integer
          minimum: 0
      responses:
        '200':
          description: Log Messages
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SystemdLogMessages'
                type: array
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /security_log/log_messages/{id}:
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Delete Log Messages
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  schemas:
    IntrusionLog:
      properties:
        id:
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
        service:
          type: string
        server:
          type: string
        datetime:
          format: date-time
          type: string
        host:
          type: string
        username:
          nullable: true
          type: string
      type: object
      required:
      - id
      - service
      - server
      - datetime
      - host
    IntrusionLogUpdate:
      properties:
        updates:
          items:
            $ref: '#/components/schemas/IntrusionLog'
          type: array
      type: object
      required:
      - updates
    HostCountry:
      properties:
        host:
          description: Host
          type: string
        code:
          description: Country Code
          type: string
        ipaddr:
          description: IP Address
          nullable: true
          type: string
        created_at:
          description: Created At
          format: date-time
          type: string
      type: object
      required:
      - host
      - code
      - created_at
    HostCountryUpdate:
      properties:
        updates:
          items:
            properties:
              host:
                type: string
              code:
                type: string
              ipaddr:
                nullable: true
                type: string
              created_at:
                format: date-time
                type: string
            type: object
            required:
            - host
            - code
            - created_at
          type: array
      type: object
      required:
      - updates
    LoggedUser:
      properties:
        email:
          description: Email Address
          type: string
        session:
          description: Session Id
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
        secret_key:
          description: Secret Key
          type: string
      type: object
      required:
      - email
      - session
      - secret_key
    SystemdLogMessages:
      properties:
        id:
          description: ID
          format: uuid
          example: 334518f4-1bfd-4f20-9978-bfad0dc033e1
          type: string
        log_level:
          description: Log Level
          type: string
          enum:
          - Debug
          - Info
          - Warning
          - Error
        log_unit:
          description: Log Unit
          nullable: true
          type: string
        log_message:
          description: Log Message
          type: string
        log_timestamp:
          description: Log Timestamp
          format: date-time
          type: string
        processed_time:
          description: Log Processed At Time
          format: date-time
          nullable: true
          type: string
      type: object
      required:
      - id
      - log_level
      - log_message
      - log_timestamp
